apiVersion: v1
kind: Service
metadata: 
  name: client-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 # port that the other objects target if they want to access the multi client. (Access the service port)
      targetPort: 3000 # multi-client pod (in the container)